name       : isoimagewriter
version    : 1.0.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/isoimagewriter/1.0.0/isoimagewriter-1.0.0.tar.xz : a69022303ec1beb6b7b4f0d68e59e4199d3c9868767cb9eb23c6dd1999e06a5d
license    : GPL-3.0-or-later
component  : system.utils
summary    : ISO Image Writer is a KDE tool to write a .iso file to a USB disk.
description: |
    ISO Image Writer is a KDE tool to write a .iso file to a USB disk.
builddeps  :
    - gpgme-qt-devel
    - karchive-devel
    - kcoreaddons-devel
    - kcrash-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - solid-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
